### ISSUE TITLE
Can you apply gradientify to more than one element at a time?

### ISSUE THREAD

**Issue by eddiejibson** [codefog/jquery-gradientify#1]
Hi,

Been wondering how I could apply gradientify to two elements at a time. This is because two separate elements close to one another would look better with one gradient for the whole background, instead of two separately. If so, how?

Cheers.

**Comment by qzminski** [comment]
Hey, not sure if I understand correctly but to apply the gradient to the two elements you simply initialize the script individually per each element:

```js
$('#foo, #bar').gradientify({ ... });

// or

$('#foo').gradientify({ ... });
$('#bar').gradientify({ ... });
```

**Comment by eddiejibson** [comment]
Hi, 

It's regarding so they share one gradient, if you want I can share a screenshot to show you.

Cheers.

**Comment by qzminski** [comment]
The visualization of what you want to achieve would be helpful indeed.

**Comment by eddiejibson** [comment]
Hi,

See the question here: http://imgur.com/a/tmXsg

Thank-you.

**Comment by qzminski** [comment]
I think either you have to rework the markup and css so the background is applied to the one element behind them or if that's not possible, the first element should get the gradient going e.g. from A to B and the second element from B to C. This way the division should no longer be visible because the same color will be on the edge of both boxes.

Yet I would still recommend to rework the markup and css to achieve the best result.

**Comment by eddiejibson** [comment]
Great, thank-you for your help and creating such a useful asset, it's very much appreciated.
